In [75]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# 1. Creating Array 

In [76]:
#Creating 1D arrays from lists
list = [3, 2, -5, -8, 0, 9, 7, 6, 1] 
array = np.array(list) 
array 

array([ 3,  2, -5, -8,  0,  9,  7,  6,  1])

In [77]:
#Creating 2D arrays from lists
lists = [[3, 2, 5], [9, 7, 1], [4, 3, 6]] 
array_2d=np.array(lists) 
array_2d

array([[3, 2, 5],
       [9, 7, 1],
       [4, 3, 6]])

In [78]:
np.arange(-3,4)

array([-3, -2, -1,  0,  1,  2,  3])

In [79]:
np.arange(-3, 4, 3)

array([-3,  0,  3])

In [80]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [81]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 4.67293691e-307],
       [1.42413555e-306, 1.78019082e-306]])

In [86]:
np.diag((2,1,4))

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 4]])

In [87]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [88]:
#random numbers between 0 and 1
np.random.random(3)

array([0.61004629, 0.54011266, 0.89966325])

In [89]:
np.random.random((1,3))

array([[0.84203192, 0.73870441, 0.78775171]])

In [90]:
np.random.normal(0,1,10)

array([ 0.56822033,  0.86369389, -0.32572782,  0.31931001,  0.92597955,
       -0.72909494,  0.63577724,  0.19834752,  1.43749403, -1.36238447])

In [91]:
#number between 0 and 150
np.random.randint(150)

53

In [92]:
#15 random number
np.random.rand(15)

array([0.20516865, 0.50204426, 0.46523196, 0.11459312, 0.89105576,
       0.71772061, 0.82541289, 0.52915757, 0.00902584, 0.86192665,
       0.10482088, 0.19809395, 0.76449452, 0.59816445, 0.82543037])

# 2. Exploring Data

In [93]:
#shape--->dimention of array
#dtype--->variable type
#type---->type of array (class of the array)
#size---->number of elements in array
#ndim---->n dimention 
print(type(array)) 
print(type(array_2d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [94]:
print(array.shape)
print(array_2d.shape) 

(9,)
(3, 3)


In [95]:
print(array.dtype)
print(array_2d.dtype)

int32
int32


In [96]:
print(array.size)
print(array_2d.size)

9
9


In [97]:
print(array.ndim)
print(array_2d.ndim)

1
2


# 3. Filtering

In [98]:
array[0]

3

In [99]:
array_2d[0,2]

5

In [100]:
array_2d[0:2,:]

array([[3, 2, 5],
       [9, 7, 1]])

In [101]:
#enter index-->get value
array[[2,5]]

array([-5,  9])

In [102]:
array[array>5]

array([9, 7, 6])

In [103]:
array_2d[array_2d%2==0]

array([2, 4, 6])

In [104]:
np.where(array>7)

(array([5], dtype=int64),)

In [105]:
#np.where(condition, value_if_true, value_if_false)

np.where(array>0,'positive','Negative')

array(['positive', 'positive', 'Negative', 'Negative', 'Negative',
       'positive', 'positive', 'positive', 'positive'], dtype='<U8')

In [106]:
#np.select(conditions, choices, default='value_for_no_match')

conditions = [array < 0, array == 0, array > 0]
choices = ['Negative', 'Zero', 'Positive']
np.select(conditions,choices)

array(['Positive', 'Positive', 'Negative', 'Negative', 'Zero', 'Positive',
       'Positive', 'Positive', 'Positive'], dtype='<U8')

In [107]:
np.where(array % 2 == 0, 'odd', 'even')

array(['even', 'odd', 'even', 'odd', 'odd', 'even', 'even', 'odd', 'even'],
      dtype='<U4')

# 4. Array Mathematics


In [108]:
np.sum(array)

15

In [109]:
np.sum(array_2d)

40

In [110]:
#axis=0 ---->column
#axis=1 ---->

np.sum(array_2d,axis=0)

array([16, 12, 12])

In [111]:
#min number in each
np.min(array_2d,axis=0)

array([3, 2, 1])

In [112]:
np.min(array_2d)

1

In [113]:
Max=np.max(array)
Mean=np.mean(array)
Median=np.median(array)
Variance=np.var(array)
Max,Mean,Median,Variance

(9, 1.6666666666666667, 2.0, 27.11111111111111)

In [114]:
np.cumsum(array_2d)

array([ 3,  5, 10, 19, 26, 27, 31, 34, 40])

In [115]:
np.cumsum(array_2d,axis=0)

array([[ 3,  2,  5],
       [12,  9,  6],
       [16, 12, 12]])

In [116]:
np.cos(array)

array([-0.9899925 , -0.41614684,  0.28366219, -0.14550003,  1.        ,
       -0.91113026,  0.75390225,  0.96017029,  0.54030231])

In [117]:
np.abs(array)

array([3, 2, 5, 8, 0, 9, 7, 6, 1])

In [118]:

np.mod(array,4)

array([3, 2, 3, 0, 0, 1, 3, 2, 1], dtype=int32)

In [119]:
np.power(array,2)

array([ 9,  4, 25, 64,  0, 81, 49, 36,  1], dtype=int32)

In [120]:
np.round(3.68528)

4.0

In [121]:
np.round(3.68528,2)

3.69

In [122]:
np.floor(3.68528)

3.0

In [123]:
np.ceil(3.68528)

4.0

In [124]:
np.random.shuffle(array_2d)
array_2d

array([[4, 3, 6],
       [3, 2, 5],
       [9, 7, 1]])

In [125]:
np.random.shuffle(array)
array

array([ 3,  6,  2,  0, -8, -5,  1,  7,  9])

# 5. Data Transformation

In [126]:
np.arange(1000000).sum()

1783293664

In [127]:
array + 3 

array([ 6,  9,  5,  3, -5, -2,  4, 10, 12])

In [128]:
array_2d * 2 

array([[ 8,  6, 12],
       [ 6,  4, 10],
       [18, 14,  2]])

In [129]:
#should have same size
array_a = np.array([[1, 2,0], [4,6,5],[1,2,0]])
array_2d*array_a

array([[ 4,  6,  0],
       [12, 12, 25],
       [ 9, 14,  0]])

In [130]:
#Matrix Multiplication
np.multiply(array_2d,array_a)

array([[ 4,  6,  0],
       [12, 12, 25],
       [ 9, 14,  0]])

In [131]:
array_2d+array_a

array([[ 5,  5,  6],
       [ 7,  8, 10],
       [10,  9,  1]])

In [132]:
# Dot product of two arrays (3,3)*(3,2)
array_b = np.array([[1, 2], [4,6],[1,2]])
np.dot(array_2d,array_b)

array([[22, 38],
       [16, 28],
       [38, 62]])

In [133]:
np.flip(array_2d)

array([[1, 7, 9],
       [5, 2, 3],
       [6, 3, 4]])

In [134]:
np.transpose(array_2d)

array([[4, 3, 9],
       [3, 2, 7],
       [6, 5, 1]])

In [135]:
array_2d.T

array([[4, 3, 9],
       [3, 2, 7],
       [6, 5, 1]])

In [136]:
np.sort(array)

array([-8, -5,  0,  1,  2,  3,  6,  7,  9])

In [137]:
np.split(array_2d,3)

[array([[4, 3, 6]]), array([[3, 2, 5]]), array([[9, 7, 1]])]

# 6. Reshape

In [138]:
array_2d.flatten()

array([4, 3, 6, 3, 2, 5, 9, 7, 1])

In [139]:
array_2d.reshape((9,1))

array([[4],
       [3],
       [6],
       [3],
       [2],
       [5],
       [9],
       [7],
       [1]])

In [140]:
np.stack(array_2d)

array([[4, 3, 6],
       [3, 2, 5],
       [9, 7, 1]])